on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.1"

      # Build the production binary
      - name: Build Binary
        run: ./scripts/buildprod.sh

      # Authenticate with Google Cloud
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Set up the Google Cloud SDK
      - name: Setup GCP SDK
        uses: google-github-actions/setup-gcloud@v2

      # Verify gcloud CLI setup
      - name: Use gcloud cli
        run: gcloud info

      # Check if any files in ./ui/static/*/* were updated
      - name: Detect changes in UI static files
        id: changed_files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./ui/static/ > changed_files.txt
          cat changed_files.txt

      # Upload only the changed files to GCP
      - name: Upload changed files to GCP
        if: ${{ steps.changed_files.outputs.files != '' }}
        run: |
          while IFS= read -r file; do
            new_path=$(echo "$file" | sed 's|^ui/||')
            gcloud storage cp "$file" "gs://timengledev-blog/$new_path"
          done < changed_files.txt

      # Build and push the Docker image to Artifact Registry
      - name: Build & Push image to Artifact Registry
        run: |
          gcloud builds submit \
            --tag us-west1-docker.pkg.dev/timengledev-blog/app/timengledev-blog:latest .

      # Deploy the container image to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy timengledev-blog \
            --image us-west1-docker.pkg.dev/timengledev-blog/app/timengledev-blog:latest \
            --region us-west1 \
            --allow-unauthenticated \
            --project timengledev-blog \
            --max-instances=4
